### ISSUE TITLE
Support optional positional arguments - like &rest?

### ISSUE THREAD

**Issue by sebasmonia** [simkoc/cl-argparse#1]
I have a tool that accepts "up to" 3 arguments. I implemented this using three optional parameters, but I would have liked something like the following:

`do-stuff arg1`
`do-stuff arg1 arg2`
`do-stuff arg1 arg2 arg3`

No idea whether it should throw an error if more arguments are used, or it should be like `&rest` and just give you everything else in a list.

Coming from Python, I found this package very easy to use :) thank you!

**Comment by simkoc** [comment]
If I understand you correctly you want optional positional arguments? This would come with severe restrictions on what values those positional can have i.e.

```
do-stuff arg -flag --optional test
```

do we have 4 optional positional with the values `arg` `-flag` `--optional` and `test` or due we have one optional, a flag, and a positional?

It would be possible to prohibit the use of `-` or `--` in the values provided to those positional, but the parsing would still be a pain.

**Comment by sebasmonia** [comment]
You are right, I can see a lot of complexities on this. 
The "simplest" option I can think is a final positional argument (`add-positional-rest`?) that returns everything after it with no parsing, but it would cause surprising behaviour in many cases, if the user adds `--flag` later in the line.

Maybe there's another way to get the input I want, or maybe it was a bad idea to being with :sweat_smile:

**Comment by simkoc** [comment]
depending on the complexity of the arguments and if you must have at least one you could provide the arguments within one string as csv you then split and process.

```
do-stuff "arg1,arg2,ar3"
```

**Comment by sebasmonia** [comment]
Closing this as there doesn't seem to be any demand and it (potentially) creates a lot of problems.
